ch_cookie_consent:
    consent_categories:
        - analytics
        - marketing
        - social_media
        - functional
    cookie_settings:
        name_prefix: 'symfotest'
        cookies:
            consent_cookie:
                http_only: false
    theme: light
    use_logger: true
    position: 'top' # top, bottom
    simplified: false # When set to true the user can only deny or accept all cookies at once
#    form_action: cookie_consent_form_action # When set, xhr-Requests will only be sent to this route. Take care of having the route available.
    csrf_protection: true # The cookie consent form is csrf protected or not
