ch_cookie_consent:
    theme: light
#    categories: ['marketing']
    use_logger: true
    position: 'top' # top, bottom
    simplified: false # When set to true the user can only deny or accept all cookies at once
#    http_only: false # Sets HttpOnly on cookies
#    form_action: cookie_consent_form_action # When set, xhr-Requests will only be sent to this route. Take care of having the route available.
    csrf_protection: true # The cookie consent form is csrf protected or not
