cookie_consent:
  cookie_settings:
    name_prefix: '' # string, any string you like to prefix the cookie names with
    cookies:
      consent_cookie:
        expires: 'P180D' # available values: PHP formatted date string, 'P180D' (180 days), 'P1Y' (1 year) etc.
        domain: null # string or null, domain name, e.g. 'example.com'; null means 'use the current domain'
        secure: true # boolean, enable or disable transport only over https
        http_only: true # boolean, refer to mdn docs for more info
        same_site: 'lax' # available values: 'strict', 'lax', 'none'
      consent_key_cookie:
        expires: 'P180D'
        domain: null
        secure: true
        http_only: true
        same_site: 'lax'
      consent_categories_cookie:
        expires: 'P180D'
        secure: true
        http_only: true
        same_site: 'lax'
  consent_categories: # Below are the default supported categories
    - 'analytics'
    - 'tracking'
    - 'marketing'
    - 'social_media'
  persist_consent: true # boolean; logs user actions to database
  position: 'dialog' # available values: 'top', 'bottom', 'dialog'
#  form_action: app_cookie_consent # When set, xhr-Requests will only be sent to this route. Take care of having the route available.
  csrf_protection: true # boolean; enable or disable csrf protection for the form