twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
#        - '@CookieConsent/form/cookie_consent_form_theme.html.twig'

when@test:
    twig:
        strict_variables: true
